# People on Banknotes

Whose faces appear on banknotes?

The file `people-on-banknotes.csv` contains data about individuals featured on banknotes from 38 countries. This dataset spans all 22 subregions and sub-subregions of the world, as defined by the United Nations Statistics Division's geoscheme.

It profiles 241 people, detailing their occupations and the year they first appeared on a banknote. Additionally, it includes their year of death — or `NaN` if they were still alive when the dataset was compiled.

Most banknotes were issued after the featured individual’s death. The column `first_death_diff` calculates the difference between the year of their first appearance on a banknote and their year of death (or remains `NaN` if the person was still living at the time of curation).

In [17]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'people-on-banknotes.csv'.

# from google.colab import files
# uploaded = files.upload()

In [18]:
import pandas as pd

df = pd.read_csv('people-on-banknotes.csv')
df

,country,currency,name,gender,occupation,value,first_appearance,death,first_death_diff,currency_code
0,Argentina,Argentine Peso,Eva Perón,F,Activist,100,2012,1952,60.0,ARS
1,Argentina,Argentine Peso,Julio Argentino Roca,M,Head of Gov't,100,1988,1914,74.0,ARS
2,Argentina,Argentine Peso,Domingo Faustino Sarmiento,M,Head of Gov't,50,1999,1888,111.0,ARS
3,Argentina,Argentine Peso,Juan Manuel de Rosas,M,Politician,20,1992,1877,115.0,ARS
4,Argentina,Argentine Peso,Manuel Belgrano,M,Founder,10,1970,1820,150.0,ARS
...,...,...,...,...,...,...,...,...,...,...
274,Venezuela,Venezuelan Bolivar,Francisco de Miranda,M,Military,200,1968,1816,152.0,VES
275,Venezuela,Venezuelan Bolivar,Simón Rodrigues,M,Educator,20,2007,1854,153.0,VES
276,Venezuela,Venezuelan Bolivar,Ezequiel Zamora,M,Military,100,2018,1860,158.0,VES
277,Venezuela,Venezuelan Bolivar,Rafael Urdaneta,M,Head of Gov't,10,2018,1845,173.0,VES
278,Venezuela,Venezuelan Bolivar,José Félix Ribas,M,Military,5,2018,1815,203.0,VES

### Quick cleaning

The same person can appear on multiple banknotes. Below we drop the `value` column and remove duplicate people.

In [19]:
df = df.drop(columns=['value'])
df = df.drop_duplicates(subset="name")
df

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
0,Argentina,Argentine Peso,Eva Perón,F,Activist,2012,1952,60.0,ARS
1,Argentina,Argentine Peso,Julio Argentino Roca,M,Head of Gov't,1988,1914,74.0,ARS
2,Argentina,Argentine Peso,Domingo Faustino Sarmiento,M,Head of Gov't,1999,1888,111.0,ARS
3,Argentina,Argentine Peso,Juan Manuel de Rosas,M,Politician,1992,1877,115.0,ARS
4,Argentina,Argentine Peso,Manuel Belgrano,M,Founder,1970,1820,150.0,ARS
...,...,...,...,...,...,...,...,...,...
274,Venezuela,Venezuelan Bolivar,Francisco de Miranda,M,Military,1968,1816,152.0,VES
275,Venezuela,Venezuelan Bolivar,Simón Rodrigues,M,Educator,2007,1854,153.0,VES
276,Venezuela,Venezuelan Bolivar,Ezequiel Zamora,M,Military,2018,1860,158.0,VES
277,Venezuela,Venezuelan Bolivar,Rafael Urdaneta,M,Head of Gov't,2018,1845,173.0,VES
278,Venezuela,Venezuelan Bolivar,José Félix Ribas,M,Military,2018,1815,203.0,VES

### Project Ideas

- What proportion of individuals featured are male versus female?
	- Hint: Use `value_counts(normalize=True)` to calculate percentages.

- Are writers or politicians more commonly depicted?

- What percentage of featured individuals are musicians?

- What percentage of banknotes were issued before the person’s death?
	- Hint: Look for negative values or NaN in `first_death_diff`.

- Who is the oldest historical figure in the dataset?

- Which countries feature the oldest historical figures on their banknotes?
	- Hint: Group by country and aggregate the year of death using the median. Sort the results.

- What percentage of individuals died at least 100 years before appearing on a banknote?

- Which individuals appeared on a banknote just one year after their death?

In [20]:
# YOUR CODE HERE (add additional cells as needed)

df["gender"]

0      F
1      M
2      M
3      M
4      M
      ..
274    M
275    M
276    M
277    M
278    M
Name: gender, Length: 241, dtype: str

In [21]:
df["gender"].value_counts(normalize=True)

gender
M    0.780083
F    0.219917
Name: proportion, dtype: float64

In [22]:
df["occupation"]

0           Activist
1      Head of Gov't
2      Head of Gov't
3         Politician
4            Founder
           ...
274         Military
275         Educator
276         Military
277    Head of Gov't
278         Military
Name: occupation, Length: 241, dtype: str

In [23]:
df["occupation"].value_counts(normalize=True)

occupation
Writer              0.186722
Head of Gov't       0.157676
Politician          0.112033
Founder             0.103734
Revolutionary       0.087137
STEM                0.066390
Military            0.053942
Visual Artist       0.053942
Musician            0.049793
Monarch             0.049793
Other               0.020747
Activist            0.016598
Educator            0.016598
Religious figure    0.012448
Performer           0.012448
Name: proportion, dtype: float64

In [24]:
df["first_death_diff"]

0       60.0
1       74.0
2      111.0
3      115.0
4      150.0
       ...
274    152.0
275    153.0
276    158.0
277    173.0
278    203.0
Name: first_death_diff, Length: 241, dtype: float64

In [25]:
df.query("first_death_diff < 0")

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
14,Bangladesh,Bangladeshi Taka,Bangabandhu Sheikh Mujibur Rahman,M,Founder,1972,1975,-3.0,BDT
119,Indonesia,Indonesian Rupiah,Soekarno,M,Head of Gov't,1945,1970,-25.0,IDR
135,Jamaica,Jamaican Dollar,Michael Norman Manley,M,Head of Gov't,1970,1992,-22.0,JMD
150,Malawi,Malawian Kwacha,Dr. Hastings Kamuzu Banda,M,Head of Gov't,1971,1997,-26.0,MWK
151,Malawi,Malawian Kwacha,Rose Lomathinda Chibambo,F,Politician,2012,2016,-4.0,MWK
168,New Zealand,New Zealand Dollar,Edmund Hillary,M,Other,1992,2008,-16.0,NZD
182,Papua New Guinea,Papua New Guinean Kina,Michael Somare,M,Founder,1989,2021,-32.0,PGK
216,South Africa,South African Rand,Nelson Mandela,M,Head of Gov't,2012,2013,-1.0,ZAR
235,Turkey,Turkish Lira,Kemal Atatürk,M,Founder,1927,1938,-11.0,TRY

In [26]:
df["first_death_diff"].isna().sum()

np.int64(2)

In [27]:
(9+2)/241*100

4.564315352697095

In [28]:
df["death"]

0      1952
1      1914
2      1888
3      1877
4      1820
       ...
274    1816
275    1854
276    1860
277    1845
278    1815
Name: death, Length: 241, dtype: str

In [29]:
df.sort_values(by="death")

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
234,Tunisia,Tunisian Dinar,Hannibal,M,Military,2013,-183,2196.0,TND
256,Ukraine,Ukrainian Hryvna,Volodymyr the Great,M,Monarch,1992,1015,977.0,UAH
255,Ukraine,Ukrainian Hryvna,Yaroslav the Wise,M,Monarch,1992,1054,938.0,UAH
149,Kyrgyzstan,Kyrgystani Som,Jusup Balasagyn,M,Writer,2000,1077,923.0,KGS
113,Georgia,Georgian Lari,King David IV,M,Monarch,1995,1125,870.0,GEL
...,...,...,...,...,...,...,...,...,...
63,Colombia,Colombian Peso,Gabriel García Márquez,M,Writer,2015,2014,1.0,COP
151,Malawi,Malawian Kwacha,Rose Lomathinda Chibambo,F,Politician,2012,2016,-4.0,MWK
182,Papua New Guinea,Papua New Guinean Kina,Michael Somare,M,Founder,1989,2021,-32.0,PGK
13,Australia,Australian Dollar,Queen Elizabeth II,F,Monarch,1961,NaN,NaN,AUD
37,Bolivia,Bolivian Boliviano,Genoveva Ríos,F,Other,2018,NaN,NaN,BOB

In [30]:
df["death"] = pd.to_numeric(df["death"], errors="coerce")
df.groupby("country")["death"].median()

country
Argentina                1888.0
Australia                1936.5
Bangladesh               1975.0
Bolivia                  1839.5
Canada                   1943.5
Cape Verde               2010.0
Chile                    1879.0
China                    1976.0
Colombia                 1948.0
Costa Rica               1947.0
Czech Republic           1869.0
Dominican Republic       1905.0
England                  1902.5
Georgia                  1915.0
Iceland                  1845.0
Indonesia                1947.5
Israel                   1956.5
Jamaica                  1967.0
Japan                    1901.0
Kyrgyzstan               1942.0
Malawi                   1966.5
Mexico                   1892.5
New Zealand              1943.5
Nigeria                  1976.0
Papua New Guinea         2021.0
Peru                     1945.0
Philippines              1948.0
Serbia                   1927.0
South Africa             2013.0
South Korea              1560.5
Sweden                   1996.0
São Tomé and Príncipe    1779.5
Tunisia                  1943.5
Turkey                   1936.0
Ukraine                  1817.5
United States            1826.0
Uruguay                  1931.0
Venezuela                1849.5
Name: death, dtype: float64

In [31]:
df["death"] = pd.to_numeric(df["death"], errors="coerce")
df.groupby("country")["death"].median().sort_values()

country
South Korea              1560.5
São Tomé and Príncipe    1779.5
Ukraine                  1817.5
United States            1826.0
Bolivia                  1839.5
Iceland                  1845.0
Venezuela                1849.5
Czech Republic           1869.0
Chile                    1879.0
Argentina                1888.0
Mexico                   1892.5
Japan                    1901.0
England                  1902.5
Dominican Republic       1905.0
Georgia                  1915.0
Serbia                   1927.0
Uruguay                  1931.0
Turkey                   1936.0
Australia                1936.5
Kyrgyzstan               1942.0
New Zealand              1943.5
Canada                   1943.5
Tunisia                  1943.5
Peru                     1945.0
Costa Rica               1947.0
Indonesia                1947.5
Philippines              1948.0
Colombia                 1948.0
Israel                   1956.5
Malawi                   1966.5
Jamaica                  1967.0
Bangladesh               1975.0
China                    1976.0
Nigeria                  1976.0
Sweden                   1996.0
Cape Verde               2010.0
South Africa             2013.0
Papua New Guinea         2021.0
Name: death, dtype: float64

In [32]:
(df["first_death_diff"] >= 100).value_counts(normalize=True) * 100

first_death_diff
False    66.804979
True     33.195021
Name: proportion, dtype: float64

In [33]:
df[df["first_death_diff"] == 1]

,country,currency,name,gender,occupation,first_appearance,death,first_death_diff,currency_code
63,Colombia,Colombian Peso,Gabriel García Márquez,M,Writer,2015,2014.0,1.0,COP
173,Nigeria,Nigerian Naira,General Murtala Mohammed,M,Head of Gov't,1977,1976.0,1.0,NGN
190,Philippines,Philippine Piso,Corazon C. Aquino,F,Head of Gov't,2010,2009.0,1.0,PHP
191,Philippines,Philippine Piso,Manuel A. Roxas,M,Head of Gov't,1949,1948.0,1.0,PHP